import requests

#call's powerlyric's API to obtain lyrics for a specific song
def obtain_lyrics(song, artist):
    url = "https://powerlyrics.p.rapidapi.com/getlyricsfromtitleandartist"

    querystring = {"title":song,"artist":artist}

    headers = {
	    "X-RapidAPI-Key": "YOUR API KEY",
	    "X-RapidAPI-Host": "powerlyrics.p.rapidapi.com"
    }
    response = requests.request("GET", url, headers=headers, params=querystring)
    json_lyrics = response.json()
    print(json_lyrics)
    lyrics = json_lyrics['lyrics']
    return lyrics

#separates lyrics into an array of verses 
def create_array(lyrics):
    lyric_array = []
    paragraph = ""
    for i in range(0, len(lyrics) - 1):
        paragraph = paragraph + lyrics[i]
        if lyrics[i] == '\n' and lyrics[i + 1] == '\n':
            lyric_array.append(paragraph)
            paragraph = ""
    return lyric_array

#call's Open AI's text generator API to obtain a description of an image based on the imagery described in each verse + themes present in the verse
def obtain_image_desc(lyrics):
    #dict of parameters to pass into API request
    my_headers = { 'Content-Type' : 'application/json', 'Authorization' : 'Bearer YOUR API TOKEN'}
    #lyrics = "The drink you spilt all over me / 'Lover's Spit' left on repeat / My mom and dad let me stay home / It drives you crazy getting old"
    
    #API endpoint URL
    url = 'https://api.openai.com/v1/completions'

    model_info = {
        'model': 'text-davinci-003',
        'prompt': "Provide descriptive language that could be used to construct an image based on the setting present in these lyrics: " + lyrics + " with the response being under 350 characters (including spaces)",
        'max_tokens': 2048,
        'temperature': 0,
    }

    #API request to obtain data for each song 
    response = requests.post(url, headers=my_headers, json=model_info)
    json_description = response.json()
    return json_description['choices'][0]['text']

#call's DALL-E API to obtain the url of an image generated by DALL-E based on the description provided by the Open AI text generator 
def obtain_image_url(image_desc, art_style):
    my_headers = { 'Content-Type' : 'application/json', 'Authorization' : 'Bearer YOUR API TOKEN'}
    url = 'https://api.openai.com/v1/images/generations'
    
    image_param = {
        'prompt':image_desc + " " + art_style,
        'n':1,
        'size':'1024x1024'
    }

    response = requests.post(url, headers=my_headers, json=image_param)
    json_images = response.json()
    return json_images['data'][0]['url']

#def create_movie():